// Demo seed data for recording walkthroughs.
// Call seedDemoData() to replace all storage with realistic fixture data.
// Call clearDemoData() to wipe back to factory defaults.

import {
  githubAuthItem,
  githubHiddenItem,
  githubPrsItem,
  githubReposItem,
  githubUiItem,
  listsItem,
  todosItem,
} from "~/lib/storage"
import { inboxDefault } from "~/lib/todos/types"
import type { PullRequest, RepoMeta } from "~/lib/github/types"
import type { ListMeta, TodoItem } from "~/lib/todos/types"

// ── date helpers ──────────────────────────────────────────────────────────────

/** Midnight of today + offsetDays (negative = past). */
function dayMs(offsetDays: number): number {
  const d = new Date()
  d.setHours(0, 0, 0, 0)
  return d.getTime() + offsetDays * 86_400_000
}

/** Date.now() shifted by offsetDays. */
function ago(offsetDays: number): number {
  return Date.now() - offsetDays * 86_400_000
}

// ── avatars ───────────────────────────────────────────────────────────────────
// Public GitHub avatars — low-numbered user IDs are definitely public.

const AV = {
  alex:   "https://avatars.githubusercontent.com/u/583231?v=4",
  sarah:  "https://avatars.githubusercontent.com/u/100?v=4",
  marcus: "https://avatars.githubusercontent.com/u/101?v=4",
  priya:  "https://avatars.githubusercontent.com/u/102?v=4",
  james:  "https://avatars.githubusercontent.com/u/103?v=4",
  tom:    "https://avatars.githubusercontent.com/u/104?v=4",
}

// ── GitHub pull requests ──────────────────────────────────────────────────────

const DEMO_PRS: PullRequest[] = [
  // ── Authored by the demo user ──────────────────────────────────────────────
  {
    id: "acmecorp/web-platform#247",
    number: 247,
    title: "feat: redesign dashboard onboarding flow",
    url: "https://github.com/acmecorp/web-platform/pull/247",
    repo: "acmecorp/web-platform",
    author: "alex-dev",
    authorAvatarUrl: AV.alex,
    isDraft: false,
    state: "open",
    headRef: "feat/onboarding-redesign",
    baseRef: "main",
    createdAt: ago(2),
    updatedAt: ago(0),
    commentsCount: 4,
    reviewDecision: "review_required",
    reviewers: [
      { login: "sarah-k",  avatarUrl: AV.sarah,  state: "pending" },
      { login: "marcus-t", avatarUrl: AV.marcus, state: "pending" },
    ],
    ciState: "success",
    failingChecks: 0,
    totalChecks: 8,
    mergeState: "clean",
    overallState: "blocked",
    fromTab: ["mine"],
  },
  {
    id: "acmecorp/backend-api#891",
    number: 891,
    title: "fix: resolve race condition in payment webhook handler",
    url: "https://github.com/acmecorp/backend-api/pull/891",
    repo: "acmecorp/backend-api",
    author: "alex-dev",
    authorAvatarUrl: AV.alex,
    isDraft: false,
    state: "open",
    headRef: "fix/webhook-race-condition",
    baseRef: "main",
    createdAt: ago(5),
    updatedAt: ago(1),
    commentsCount: 12,
    reviewDecision: "changes_requested",
    reviewers: [
      { login: "priya-m", avatarUrl: AV.priya, state: "changes_requested" },
      { login: "james-c", avatarUrl: AV.james, state: "approved" },
    ],
    ciState: "success",
    failingChecks: 0,
    totalChecks: 12,
    mergeState: "clean",
    overallState: "blocked",
    fromTab: ["mine"],
  },
  {
    id: "acmecorp/web-platform#156",
    number: 156,
    title: "chore: upgrade React to v19 and migrate to new JSX transform",
    url: "https://github.com/acmecorp/web-platform/pull/156",
    repo: "acmecorp/web-platform",
    author: "alex-dev",
    authorAvatarUrl: AV.alex,
    isDraft: false,
    state: "open",
    headRef: "chore/react-19-upgrade",
    baseRef: "main",
    createdAt: ago(8),
    updatedAt: ago(0),
    commentsCount: 3,
    reviewDecision: "approved",
    reviewers: [
      { login: "sarah-k", avatarUrl: AV.sarah, state: "approved" },
      { login: "tom-w",   avatarUrl: AV.tom,   state: "approved" },
    ],
    ciState: "pending",
    failingChecks: 0,
    totalChecks: 6,
    mergeState: "clean",
    overallState: "pending",
    fromTab: ["mine"],
  },
  {
    id: "acmecorp/infra#34",
    number: 34,
    title: "feat: add Terraform modules for EKS cluster auto-scaling",
    url: "https://github.com/acmecorp/infra/pull/34",
    repo: "acmecorp/infra",
    author: "alex-dev",
    authorAvatarUrl: AV.alex,
    isDraft: true,
    state: "open",
    headRef: "feat/eks-autoscaling",
    baseRef: "main",
    createdAt: ago(1),
    updatedAt: ago(0),
    commentsCount: 0,
    reviewDecision: "none",
    reviewers: [],
    ciState: "failure",
    failingChecks: 2,
    totalChecks: 5,
    mergeState: "unknown",
    overallState: "failed",
    fromTab: ["mine"],
  },
  // ── Awaiting review from the demo user ────────────────────────────────────
  {
    id: "acmecorp/backend-api#512",
    number: 512,
    title: "feat: implement OAuth 2.0 social login (Google, GitHub, Microsoft)",
    url: "https://github.com/acmecorp/backend-api/pull/512",
    repo: "acmecorp/backend-api",
    author: "sarah-k",
    authorAvatarUrl: AV.sarah,
    isDraft: false,
    state: "open",
    headRef: "feat/oauth-social-login",
    baseRef: "main",
    createdAt: ago(3),
    updatedAt: ago(0),
    commentsCount: 7,
    reviewDecision: "review_required",
    reviewers: [
      { login: "alex-dev", avatarUrl: AV.alex,  state: "pending" },
      { login: "james-c",  avatarUrl: AV.james, state: "approved" },
    ],
    ciState: "success",
    failingChecks: 0,
    totalChecks: 10,
    mergeState: "clean",
    overallState: "pending",
    fromTab: ["review"],
  },
  {
    id: "acmecorp/mobile-app#203",
    number: 203,
    title: "fix: crash when opening camera permissions dialog on iOS 17.2+",
    url: "https://github.com/acmecorp/mobile-app/pull/203",
    repo: "acmecorp/mobile-app",
    author: "marcus-t",
    authorAvatarUrl: AV.marcus,
    isDraft: false,
    state: "open",
    headRef: "fix/ios17-camera-crash",
    baseRef: "main",
    createdAt: ago(1),
    updatedAt: ago(0),
    commentsCount: 2,
    reviewDecision: "review_required",
    reviewers: [
      { login: "alex-dev", avatarUrl: AV.alex, state: "pending" },
    ],
    ciState: "success",
    failingChecks: 0,
    totalChecks: 4,
    mergeState: "clean",
    overallState: "pending",
    fromTab: ["review"],
  },
  {
    id: "acmecorp/backend-api#448",
    number: 448,
    title: "refactor: migrate user auth service to hexagonal architecture",
    url: "https://github.com/acmecorp/backend-api/pull/448",
    repo: "acmecorp/backend-api",
    author: "priya-m",
    authorAvatarUrl: AV.priya,
    isDraft: false,
    state: "open",
    headRef: "refactor/hexagonal-auth",
    baseRef: "main",
    createdAt: ago(6),
    updatedAt: ago(2),
    commentsCount: 18,
    reviewDecision: "commented",
    reviewers: [
      { login: "alex-dev", avatarUrl: AV.alex, state: "commented" },
      { login: "tom-w",    avatarUrl: AV.tom,  state: "approved" },
    ],
    ciState: "success",
    failingChecks: 0,
    totalChecks: 15,
    mergeState: "behind",
    overallState: "blocked",
    fromTab: ["review"],
  },
  {
    id: "acmecorp/web-platform#267",
    number: 267,
    title: "feat: real-time collaboration cursors with Yjs CRDT",
    url: "https://github.com/acmecorp/web-platform/pull/267",
    repo: "acmecorp/web-platform",
    author: "james-c",
    authorAvatarUrl: AV.james,
    isDraft: false,
    state: "open",
    headRef: "feat/yjs-collaboration",
    baseRef: "main",
    createdAt: ago(4),
    updatedAt: ago(0),
    commentsCount: 5,
    reviewDecision: "approved",
    reviewers: [
      { login: "alex-dev", avatarUrl: AV.alex,  state: "approved" },
      { login: "sarah-k",  avatarUrl: AV.sarah, state: "approved" },
    ],
    ciState: "success",
    failingChecks: 0,
    totalChecks: 8,
    mergeState: "clean",
    overallState: "ready",
    fromTab: ["review"],
  },
  {
    id: "acmecorp/web-platform#78",
    number: 78,
    title: "perf: optimize image pipeline with WebP conversion and lazy loading",
    url: "https://github.com/acmecorp/web-platform/pull/78",
    repo: "acmecorp/web-platform",
    author: "tom-w",
    authorAvatarUrl: AV.tom,
    isDraft: false,
    state: "open",
    headRef: "perf/image-pipeline",
    baseRef: "main",
    createdAt: ago(7),
    updatedAt: ago(1),
    commentsCount: 9,
    reviewDecision: "review_required",
    reviewers: [
      { login: "alex-dev", avatarUrl: AV.alex,   state: "pending" },
      { login: "marcus-t", avatarUrl: AV.marcus, state: "commented" },
    ],
    ciState: "failure",
    failingChecks: 3,
    totalChecks: 9,
    mergeState: "clean",
    overallState: "failed",
    fromTab: ["review"],
  },
]

const DEMO_REPOS: RepoMeta[] = [
  { key: "acmecorp/web-platform", enabled: true, discoveredAt: ago(30) },
  { key: "acmecorp/backend-api",  enabled: true, discoveredAt: ago(30) },
  { key: "acmecorp/mobile-app",   enabled: true, discoveredAt: ago(30) },
  { key: "acmecorp/infra",        enabled: true, discoveredAt: ago(30) },
]

// ── Todos ─────────────────────────────────────────────────────────────────────

const WORK_LIST_ID = "demo-work"
const SIDE_LIST_ID = "demo-side"
const PERSONAL_LIST_ID = "demo-personal"

const DEMO_LISTS: ListMeta[] = [
  inboxDefault(),
  {
    id: WORK_LIST_ID,
    name: "Work",
    color: "#3b82f6",
    sort: "manual",
    newTaskPosition: "bottom",
    showCompleted: "30d",
    createdAt: ago(45),
  },
  {
    id: SIDE_LIST_ID,
    name: "Side Project",
    color: "#a855f7",
    sort: "manual",
    newTaskPosition: "bottom",
    showCompleted: "30d",
    createdAt: ago(20),
  },
  {
    id: PERSONAL_LIST_ID,
    name: "Personal",
    color: "#22c55e",
    sort: "manual",
    newTaskPosition: "bottom",
    showCompleted: "30d",
    createdAt: ago(60),
  },
]

const DEMO_TODOS: TodoItem[] = [
  // ── Inbox ─────────────────────────────────────────────────────────────────
  {
    id: "d-inbox-1",
    listId: "inbox",
    text: "Review Sarah's OAuth PR",
    done: false,
    createdAt: ago(1),
    updatedAt: ago(1),
    dueAt: dayMs(0),
    order: 0,
  },
  {
    id: "d-inbox-2",
    listId: "inbox",
    text: "Respond to Marcus about design system feedback",
    done: false,
    createdAt: ago(2),
    updatedAt: ago(2),
    order: 1,
  },
  {
    id: "d-inbox-3",
    listId: "inbox",
    text: "Set up new team member's dev environment",
    done: true,
    doneAt: ago(0),
    createdAt: ago(3),
    updatedAt: ago(0),
    order: 2,
  },
  // ── Work ──────────────────────────────────────────────────────────────────
  {
    id: "d-work-1",
    listId: WORK_LIST_ID,
    text: "Write unit tests for payment webhook fix",
    done: false,
    createdAt: ago(2),
    updatedAt: ago(1),
    dueAt: dayMs(0),
    order: 0,
  },
  {
    id: "d-work-2",
    listId: WORK_LIST_ID,
    text: "Finish dashboard onboarding flow",
    done: true,
    doneAt: ago(0),
    createdAt: ago(4),
    updatedAt: ago(0),
    dueAt: dayMs(0),
    order: 1,
  },
  {
    id: "d-work-3",
    listId: WORK_LIST_ID,
    text: "Update API docs for new endpoints",
    done: false,
    createdAt: ago(3),
    updatedAt: ago(1),
    dueAt: dayMs(1),
    order: 2,
  },
  {
    id: "d-work-3a",
    listId: WORK_LIST_ID,
    parentId: "d-work-3",
    text: "Document authentication endpoints",
    done: true,
    doneAt: ago(0),
    createdAt: ago(2),
    updatedAt: ago(0),
    order: 0,
  },
  {
    id: "d-work-3b",
    listId: WORK_LIST_ID,
    parentId: "d-work-3",
    text: "Document payment and billing endpoints",
    done: false,
    createdAt: ago(2),
    updatedAt: ago(2),
    order: 1,
  },
  {
    id: "d-work-4",
    listId: WORK_LIST_ID,
    text: "Prepare Q2 performance review notes",
    done: false,
    createdAt: ago(7),
    updatedAt: ago(7),
    dueAt: dayMs(5),
    order: 3,
  },
  {
    id: "d-work-5",
    listId: WORK_LIST_ID,
    text: "Migrate legacy auth endpoints to new service layer",
    done: false,
    createdAt: ago(10),
    updatedAt: ago(3),
    dueAt: dayMs(10),
    order: 4,
  },
  // ── Side Project ──────────────────────────────────────────────────────────
  {
    id: "d-side-1",
    listId: SIDE_LIST_ID,
    text: "Record Glimpse Bar demo video",
    done: false,
    createdAt: ago(1),
    updatedAt: ago(1),
    dueAt: dayMs(0),
    order: 0,
  },
  {
    id: "d-side-2",
    listId: SIDE_LIST_ID,
    text: "Write blog post about React 19 migration experience",
    done: false,
    createdAt: ago(5),
    updatedAt: ago(5),
    dueAt: dayMs(7),
    order: 1,
  },
  {
    id: "d-side-3",
    listId: SIDE_LIST_ID,
    text: "Add dark mode to portfolio site",
    done: false,
    createdAt: ago(14),
    updatedAt: ago(14),
    order: 2,
  },
  {
    id: "d-side-4",
    listId: SIDE_LIST_ID,
    text: "Submit Glimpse Bar to Chrome Web Store",
    done: false,
    createdAt: ago(7),
    updatedAt: ago(7),
    dueAt: dayMs(14),
    order: 3,
  },
  // ── Personal ──────────────────────────────────────────────────────────────
  {
    id: "d-personal-1",
    listId: PERSONAL_LIST_ID,
    text: "Book dentist appointment",
    done: false,
    createdAt: ago(10),
    updatedAt: ago(10),
    dueAt: dayMs(-3), // overdue
    order: 0,
  },
  {
    id: "d-personal-2",
    listId: PERSONAL_LIST_ID,
    text: "Buy birthday gift for mom",
    done: false,
    createdAt: ago(2),
    updatedAt: ago(2),
    dueAt: dayMs(3),
    order: 1,
  },
  {
    id: "d-personal-3",
    listId: PERSONAL_LIST_ID,
    text: "Renew car insurance",
    done: false,
    createdAt: ago(5),
    updatedAt: ago(5),
    dueAt: dayMs(8),
    order: 2,
  },
]

// ── Public API ────────────────────────────────────────────────────────────────

export async function seedDemoData(): Promise<void> {
  await Promise.all([
    githubAuthItem.setValue({
      // Fake PAT so options page shows "connected" state. Not used for real sync.
      pat: "ghp_demo_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      login: "alex-dev",
      avatarUrl: AV.alex,
      scopes: ["repo", "read:org"],
    }),
    githubPrsItem.setValue(DEMO_PRS),
    githubReposItem.setValue(DEMO_REPOS),
    githubHiddenItem.setValue([]),
    githubUiItem.setValue({
      activeTab: "review",
      expanded: false,
      pinned: false,
      sidebarCollapsed: false,
      activeView: "review",
      refreshIntervalMin: 5,
      lastSyncAt: Date.now(),
    }),
    listsItem.setValue(DEMO_LISTS),
    todosItem.setValue(DEMO_TODOS),
  ])
}

export async function clearDemoData(): Promise<void> {
  await Promise.all([
    githubAuthItem.setValue({}),
    githubPrsItem.setValue([]),
    githubReposItem.setValue([]),
    githubHiddenItem.setValue([]),
    githubUiItem.setValue({
      activeTab: "review",
      expanded: false,
      pinned: false,
      sidebarCollapsed: false,
      activeView: "review",
      refreshIntervalMin: 5,
    }),
    listsItem.setValue([inboxDefault()]),
    todosItem.setValue([]),
  ])
}
